### ISSUE TITLE
Simulator DataSource: Single Direct does not work anymore.

### ISSUE THREAD

**Issue by Fyusel** [OpenEMS/openems#1569]
```
- [X] bug report
- [ ] feature request
```

This issue occurs since version 2021.10.0 (same for 2021.11.0 and 2021.12.0)
Last working version: 2021.9.0

When creating the "Simulator DataSource: Single Direct" component the following error occurs:

```
2021-07-14 08:09:08,180 [re.Cycle] ERROR [.direct.SingleDatasourceDirect] bundle io.openems.edge.simulator:1.0.0.202107130634 (131)[Simulator.Datasource.Single.Direct(30)] : The activate method has thrown an exception
Jul 14 08:09:08 raspberrypi java[478]: java.lang.IllegalArgumentException: Converter for value [[Ljava.lang.String;@ccf336] of type [class [Ljava.lang.String;] to type [INTEGER] is not implemented.
Jul 14 08:09:08 raspberrypi java[478]:         at io.openems.edge.common.type.TypeUtils.getAsType(TypeUtils.java:318)
Jul 14 08:09:08 raspberrypi java[478]:         at io.openems.edge.common.component.AbstractOpenemsComponent.addChannelsForProperties(AbstractOpenemsComponent.java:310)
Jul 14 08:09:08 raspberrypi java[478]:         at io.openems.edge.common.component.AbstractOpenemsComponent.addChannelsForProperties(AbstractOpenemsComponent.java:260)
Jul 14 08:09:08 raspberrypi java[478]:         at io.openems.edge.common.component.AbstractOpenemsComponent.updateContext(AbstractOpenemsComponent.java:225)
Jul 14 08:09:08 raspberrypi java[478]:         at io.openems.edge.common.component.AbstractOpenemsComponent.activate(AbstractOpenemsComponent.java:140)
Jul 14 08:09:08 raspberrypi java[478]:         at io.openems.edge.simulator.datasource.api.AbstractCsvDatasource.activate(AbstractCsvDatasource.java:39)
Jul 14 08:09:08 raspberrypi java[478]:         at io.openems.edge.simulator.datasource.single.direct.SingleDatasourceDirect.activate(SingleDatasourceDirect.java:43)
Jul 14 08:09:08 raspberrypi java[478]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Jul 14 08:09:08 raspberrypi java[478]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Jul 14 08:09:08 raspberrypi java[478]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jul 14 08:09:08 raspberrypi java[478]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Jul 14 08:09:08 raspberrypi java[478]:         at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:242)
Jul 14 08:09:08 raspberrypi java[478]:         at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
Jul 14 08:09:08 raspberrypi java[478]:         at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:678)
Jul 14 08:09:08 raspberrypi java[478]:         at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:524)
Jul 14 08:09:08 raspberrypi java[478]:         at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:318)
Jul 14 08:09:08 raspberrypi java[478]:         at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:308)
Jul 14 08:09:08 raspberrypi java[478]:         at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:342)
Jul 14 08:09:08 raspberrypi java[478]:         at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115)
Jul 14 08:09:08 raspberrypi java[478]:         at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:984)
Jul 14 08:09:08 raspberrypi java[478]:         at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:957)
Jul 14 08:09:08 raspberrypi java[478]:         at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:902)
Jul 14 08:09:08 raspberrypi java[478]:         at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:216)
Jul 14 08:09:08 raspberrypi java[478]:         at java.base/java.security.AccessController.doPrivileged(Native Method)
Jul 14 08:09:08 raspberrypi java[478]:         at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:213)
Jul 14 08:09:08 raspberrypi java[478]:         at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:114)
Jul 14 08:09:08 raspberrypi java[478]:         at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48)
Jul 14 08:09:08 raspberrypi java[478]:         at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:547)
Jul 14 08:09:08 raspberrypi java[478]:         at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:533)
Jul 14 08:09:08 raspberrypi java[478]:         at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:656)
Jul 14 08:09:08 raspberrypi java[478]:         at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.obtain(EventHandlerProxy.java:295)
Jul 14 08:09:08 raspberrypi java[478]:         at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:423)
Jul 14 08:09:08 raspberrypi java[478]:         at org.apache.felix.eventadmin.impl.tasks.HandlerTask.runWithoutDenylistTiming(HandlerTask.java:82)
Jul 14 08:09:08 raspberrypi java[478]:         at org.apache.felix.eventadmin.impl.tasks.SyncDeliverTasks.execute(SyncDeliverTasks.java:107)
Jul 14 08:09:08 raspberrypi java[478]:         at org.apache.felix.eventadmin.impl.handler.EventAdminImpl.sendEvent(EventAdminImpl.java:155)
Jul 14 08:09:08 raspberrypi java[478]:         at org.apache.felix.eventadmin.impl.security.EventAdminSecurityDecorator.sendEvent(EventAdminSecurityDecorator.java:96)
Jul 14 08:09:08 raspberrypi java[478]:         at io.openems.edge.core.cycle.CycleWorker.forever(CycleWorker.java:169)
Jul 14 08:09:08 raspberrypi java[478]:         at io.openems.common.worker.AbstractWorker$1.run(AbstractWorker.java:112)
```
The picture below shows the configuration of the simulator.

![error_singleDirect](https://user-images.githubusercontent.com/6420690/125572112-9a0db0a9-98a5-4ed2-9786-1445b0ccc62e.png)

**Comment by sfeilmeier** [comment]
Thanks for pointing this out! The bug came from creating the `_PropertyValues` Channel for the DataSource-Component. It should be fixed in #1586.
